### ISSUE TITLE
Where do I put the recorded values (calibrating dry and wet soil=

### ISSUE THREAD

**Issue by brokkolibase** [illuzn/esphome-april-soil-moisture-sensor#1]
Hi, where would I enter the recorded raw moisture readings from the dry and wet soil?
I would assume into the template.yaml file, but I wanted to make sure.

kind regards
Richard

**Comment by brokkolibase** [comment]
![Screenshot 2024-04-08 102412](https://github.com/illuzn/esphome-april-soil-moisture-sensor/assets/156225495/1195d59e-0cfd-4ad0-85ca-af69a438edb5)

**Comment by illuzn** [comment]
I've created a new branch which uses substitutions for these values instead of putting the raw values in the code itself (check testunit.yaml).

For reference do you mind telling me:
- What device are you using (i.e. is it April Bros or another manufacturer)?
- What raw values you got for minimum/ maximum?
- What soil medium you are testing in (potting mix, coconut coir, sand, etc).

**Comment by brokkolibase** [comment]
Hi sorry for the late response. I just received the april bros sensor. 
I tried to compile the testunit.yaml file, but I got the following error. 

![1](https://github.com/illuzn/esphome-april-soil-moisture-sensor/assets/156225495/73ed1b5d-d33d-46a6-ae3e-f164b8194d65)

**Comment by brokkolibase** [comment]
I´ll try the old firmware for now.

**Comment by brokkolibase** [comment]
so I tried the old version of the firmware did everything the way you described it. But the device isn´t showing up in home assistant. I checked by trying the default config that I dont have an wifi-passwd or smth like this. 
![grafik](https://github.com/illuzn/esphome-april-soil-moisture-sensor/assets/156225495/8ada137a-c2c9-4991-86d2-cc783f5c47a3)
As you can see I can install the firmware but the device just never shows up in home assistant. Also I can´t access any logs.

**Comment by brokkolibase** [comment]
![grafik](https://github.com/illuzn/esphome-april-soil-moisture-sensor/assets/156225495/71f0cc5d-d7f7-49ac-a137-6573dbae2dcb)

**Comment by brokkolibase** [comment]
Regarding the raw values I haven´t calibrated the device yet, but I´ll do so within the next few days.
The type of soil I use is standard potting mix.
I purchased one device for now, but I´ll order a few more once I see if the moisture reading is somewhat reliable.

Before I forget it, thanks for providing the code and all the instructions!

**Comment by illuzn** [comment]
Woops should be fixed... missed some quotes

Let me know how you get on with the raw values... would love to add create a table of suggested values for this.

**Comment by illuzn** [comment]
I've merged this now, working fine for me (and from the silence, for you).\

Let me know your calibrated values (I should also look into calibration as voltage decreases too).
